# ruff: noqa: UP007, UP035
"""init

Revision ID: 0001_initial
Revises:
Create Date: 2025-11-23 15:28:51.546184

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("teams_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["team_name"], ["teams.name"], name=op.f("users_team_name_fkey"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("users_team_name_idx"), "users", ["team_name"], unique=False)
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "MERGED", name="prstatus"), server_default="OPEN", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("pull_requests_author_id_fkey"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pull_requests_pkey")),
    )
    op.create_index(op.f("pull_requests_author_id_idx"), "pull_requests", ["author_id"], unique=False)
    op.create_table(
        "pr_reviewers",
        sa.Column("pr_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pr_id"], ["pull_requests.id"], name=op.f("pr_reviewers_pr_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("pr_reviewers_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pr_id", "user_id", name=op.f("pr_reviewers_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pr_reviewers")
    op.drop_index(op.f("pull_requests_author_id_idx"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("users_team_name_idx"), table_name="users")
    op.drop_table("users")
    op.drop_table("teams")
    # ### end Alembic commands ###
